<html>
<head>
	<title>500 Internal Error</title>
</head> 
<body>
	<h1>An error has occurred</h1>
	<h2><?php echo $e->getMessage(); ?></h2>
	<?php
	foreach ($e->getTrace() as $k => $t) {
		echo "<pre># $k ";

		echo (isset($t['file']))?" - ".$t['file']:'';
		echo (isset($t['class']))?" - ".$t['class']:'';
		echo (isset($t['function']))?"->".$t['function']."()":'';

		echo "</pre>\n";
	}
	?>
</body>

</html>
