<?php echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>

<head>
	<title>chicoco framework - Index</title>
	<style>
	pre {
		border: #000 1px solid;
		background: #eee;
		padding: 5px;
	}
	</style>
</head> 
<body>
		<!-- begin content -->
		<h1>Chicoco Framework</h1>
<?php echo $content ?>
		<!-- end content -->
</body>

</html>
