<h2>Hello, welcome to chicoco framework</h2>
<p>
	<b>chicoco framework</b> is a small, fast, and easy to use <a href="https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">MVC</a> framework written in PHP.
</p>

<h3>Why other MVC framework for PHP ?</h3>
<p>
Basically, because the current fast frameworks are very difficult to understand unless you have experience working with this type of applications.
</p>

<h3>What provide ?</h3>
<p>
	<b>chicoco framework</b> provide the basic structure to create web sites and web applications using <a href="https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">MVC</a>.

	<ul>
		<li>Separate the "business logic", database access and display</li>
		<li>Fully object oriented</li>
	</ul>
</p>

<h3>Structure</h3>
<p>
	<b>chicoco framework</b> directory structure is organized as follow:
	<ul>
		<li><b>conf/</b> : This directory contains the Application.ini file with the configuration directives</li>
		<li><b>controller/</b> : This directory contains the classes with the business logic</li>
		<li><b>core/</b> : This directory contains the <b>chicoco framework</b> main files</li>
		<li><b>layout/</b> : This directory contains the generic headers used to render the controller's views</li>
		<li><b>model/</b> : This directory contains the classes for database access</li>
		<li><b>public/</b> : This directory is the document root for the web site/application</li>
		<li><b>view/</b> : This directory contains one directory for the view files for each controller</li>
	</ul>
</p>

<h3>Examples</h3>
<p>
	See the <a href="/Example">examples here</a>
</p>
