<h2>Example: Using Aliases</h2>

<p>This example show how work the aliases</p>

<div><a href="/Hello/World">Alias 1: /Hello/World</a></div>
<div><a href="/Foo/Var">Alias 2: /Foo/Var</a></div>
<div><a href="/camel/Case">Alias 3: /camel/Case/</a></div>

<h2>The Code</h2>
<h3>controller/ExampleController.php</h3>
<pre>
&lt;?php

class ExampleController extends Chicoco\Controller
{
	public function init() {
	}

	public function IndexAction() {
		$this-&gt;render();
	}

	public function AliasAction() {
		$this-&gt;render();
	}
}
</pre>

<h3>conf/Application.conf</h3>
<pre>
[Aliases]
Hello/World = Example/Alias
Foo/Var = Example/Alias
camel/Case = Example/Alias
</pre>
