<h2>Example: Database Access</h2>
<table border="1">
<tr>
	<td>Username</td>
	<td>Host</td>
</tr>
<?php
foreach ($result as $r) {
	echo '<tr>'
	.'<td>'.$r['user'].'</td>'
	.'<td>'.$r['host'].'</td>'
	.'</tr>';
}
?>
</table>

<h2>The Code</h2>
<h3>controller/ExampleController.php</h3>
<pre>
&lt;?php

class ExampleController extends Chicoco\Controller
{
	public function init() {
	}

	public function IndexAction() {
		$this-&gt;render();
	}

	public function DBAccessAction() {
		$userDao = new UserDao();
		$result = $userDao-&gt;getUserByLogin('root');

		$this-&gt;setViewVar('result', $result);
		$this-&gt;render();
	}
}
</pre>

<h3>model/UserDao.php</h3>
<pre>
&lt;?php

class UserDao extends Chicoco\Dao
{
	public function getUserByLogin($user = "") {
		try {
			$this-&gt;setSql('SELECT Host, User FROM user WHERE User = :user');
			$this-&gt;clearParams();
			$this-&gt;addParam(':user', $user, PDO::PARAM_STR);
			$this-&gt;doSelect();

			return $this-&gt;_result;
		}
		catch (Exception $e) {
			$this-&gt;msgResult = $e-&gt;getMessage();
			return false;
		}
	}
}
</pre>

<h3>view/Example/DBAccess.phtml</h3>
<pre>
&lt;h2&gt;Example: Database Access&lt;/h2&gt;
&lt;table border="1"&gt;
&lt;tr&gt;
	&lt;td&gt;Username&lt;/td&gt;
	&lt;td&gt;Host&lt;/td&gt;
&lt;/tr&gt;
&lt;?php
foreach ($result as $r) {
	echo '&lt;tr&gt;'
	.'&lt;td&gt;'.$r['User'].'&lt;/td&gt;'
	.'&lt;td&gt;'.$r['Host'].'&lt;/td&gt;'
	.'&lt;/tr&gt;';
}
?&gt;
&lt;/table&gt;
</pre>
