<h2>Example: Logging things into database</h2>

<table>
	<tr>
		<th>timestamp</th>
		<th>level</th>
		<th>message</th>
	</tr>
	<?php
	foreach ($logs as $l) {
		echo "<tr>"
		."<td>".$l['timestamp']."</td>"
		."<td>".$l['level']."</td>"
		."<td>".$l['message']."</td>"
		."</tr>";
	}
	?>
</table>

<h2>The Code</h2>
<h3>controller/ExampleController.php</h3>
<pre>
&lt;?php

class ExampleController extends Controller
{
	public function init() {
	}

	public function IndexAction() {
		$this-&gt;render();
	}

	public function LoggingAction() {

		// Overwrite the _log attribure
		$this-&gt;_log = new LogDb();

		$this-&gt;logInfo("This is a info log");
		$this-&gt;logWarning("This is a warning log message");
		$this-&gt;logError("This is a error log message");

		$logDao = new LogDao();
		$logs = $logDao-&gt;getLogs();

		$this-&gt;setViewVar('logs', $logs);

		$this-&gt;render();
	}
</pre>

<h3>model/LogDao.php</h3>
<pre>
&lt;?php

class LogDao extends Dao{
	public function getLogs() {
		try {
			$this-&gt;setSql('SELECT * FROM logs ORDER BY timestamp asc');
			$this-&gt;clearParams();
			$this-&gt;doSelect();
			$result = $this-&gt;getResult();
			return $result;
		}
		catch (Exception $e) {
			$this-&gt;msgResult = $e-&gt;getMessage();
			return false;
		}
	}
}
</pre>

<h3>view/Example/Logging.phtml</h3>
<pre>
&lt;h2&gt;Example: Logging things into database&lt;/h2&gt;

&lt;table&gt;
	&lt;tr&gt;
		&lt;th&gt;timestamp&lt;/th&gt;
		&lt;th&gt;level&lt;/th&gt;
		&lt;th&gt;message&lt;/th&gt;
	&lt;/tr&gt;
	&lt;?php
	foreach ($logs as $l) {
		echo "&lt;tr&gt;"
		."&lt;td&gt;".$l['timestamp']."&lt;/td&gt;"
		."&lt;td&gt;".$l['level']."&lt;/td&gt;"
		."&lt;td&gt;".$l['message']."&lt;/td&gt;"
		."&lt;/tr&gt;";
	}
	?&gt;
&lt;/table&gt;
</pre>
