<h2>Send Email</h2>

<p><?php echo $message; ?></p>

<h2>The Code</h2>
<h3>controller/ExampleController.php</h3>
<pre>
&lt;?php

class ExampleController extends Controller
{
	public function init() {
	}

	public function IndexAction() {
		$this->render();
	}


	public function SendEmailAction() {
		$from = 'noreply@example.com';
		$to = 'atalatlae@gmail.com';
		$subject = 'test email';
		$content = '';
		$data = array(
			'mailContent' => 'Hello World',
		);

		$mail = new Mail($from, $to, $subject, $content, $data);
		$result = $mail->sendHtml();

		if ($result === true) {
			$this->setViewVar('message', 'The email was sent successfully');
		}
		else {
			$this->setViewVar('message', 'The email was not sent');
		}

		$this->render();
	}

}
</pre>
