<h2>Example: Url Params</h2>

<p>This example show how get the params that are passed in the url (inside the path)</p>

<div>
	<a href="/Example/UrlParams/foo/123456">Click here to get the $foo var from the URL</a>
</div>

<h3>$foo value is: <?php echo $foo; ?></h3>

<h2>The Code</h2>
<h3>controller/ExampleController.php</h3>
<pre>
&lt;?php

class ExampleController extends Controller
{
	public function init() {
	}

	public function IndexAction() {
		$this-&gt;render();
	}

	public function UrlParamsAction() {
		$foo = $this-&gt;getPathParams('foo');
		$this-&gt;setViewVar('foo', $foo);
		$this-&gt;render();
	}
}
</pre>

<h3>view/Example/UrlParams.phtml</h3>
<pre>
&lt;h2&gt;Example: Url Params&lt;/h2&gt;

&lt;p&gt;This example show how get the params that are passed in the url (inside the path)&lt;/p&gt;

&lt;div&gt;
	&lt;a href="/Example/UrlParams/foo/123456"&gt;Click here to get the $foo var from the URL&lt;/a&gt;
&lt;/div&gt;

&lt;h3&gt;$foo value is: &lt;?php echo $foo; ?&gt;&lt;/h3&gt;
</pre>
